#!/bin/sh
set -eu

cd "$(dirname "$0")"

ENV_FILE=etc/cocoon/.env

if [ ! -f "$ENV_FILE" ]; then
	cp etc/cocoon/.env.example "$ENV_FILE"
	echo "COCOON_ADMIN_PASSWORD=$(openssl rand -hex 32)" >>"$ENV_FILE"
	echo "COCOON_SESSION_SECRET=$(openssl rand -hex 32)" >>"$ENV_FILE"
	echo "Created $ENV_FILE"
fi

docker compose run --rm cocoon sh -exc '
  /cocoon create-rotation-key --out="${COCOON_ROTATION_KEY_PATH}"
  /cocoon create-private-jwk --out="${COCOON_JWK_PATH}"
'
