name: fogtype
services:
  https:
    image: caddy:2.11.6-alpine@sha256:c776e0c6413b544d0459665e54ec7b8b2a15000c0cbee8b254da0067b1d184ff
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/udp"
      - "443:443/tcp"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./etc/caddy:/etc/caddy
      - ./srv:/srv
      - caddy_data:/data
      - caddy_config:/config
  gts:
    image: superseriousbusiness/gotosocial:0.22.1@sha256:0078ca451dda5e8c4a8630784519f99b69f48c3dda79586a9703d4bf8ea14dae
    restart: unless-stopped
    env_file:
      - path: etc/gotosocial/.env
        required: false
    environment:
      GTS_HOST: fogtype.com
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_TRUSTED_PROXIES: 172.30.0.0/24,fded:a56c:7a13::/64
    volumes:
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
      - ./etc/gotosocial:/etc/gotosocial
      - gotosocial_data:/gotosocial/storage
    command: "--config-path /etc/gotosocial/config.yaml"
  maddy:
    image: foxcpp/maddy:0.9.6@sha256:e1074e92a452b84d1135ebe8ab831c5f541d33dcbd39e38fab740a53bbf2f97c
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    environment:
      MADDY_CONFIG: /etc/maddy/maddy.conf
      MADDY_HOSTNAME: fogtype.com
      MADDY_DOMAIN: fogtype.com
    volumes:
      - /etc/maddy:/etc/maddy
      - caddy_data:/var/lib/caddy/data:ro
      - maddy_data:/data
    entrypoint:
      - /bin/maddy
    command: run
  cocoon:
    image: ghcr.io/haileyok/cocoon:0.11.4@sha256:d8da30c852800aeffdf4b6d82fd9631c3f8b752bc1123985c5ce622f37d1fc88
    restart: unless-stopped
    env_file: etc/cocoon/.env
    volumes:
      - cocoon_data:/data
  headscale:
    image: headscale/headscale:v0.29.4@sha256:8833f828b414c0907b7e5c71da76473216fe17cce0818a166b536ec552c0903f
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "127.0.0.1:9200:9200"
    env_file:
      - path: etc/headscale/.env
        required: false
    volumes:
      - ./etc/headscale:/etc/headscale
      - headscale_data:/var/lib/headscale
    command: serve
  pocketid:
    image: ghcr.io/pocket-id/pocket-id:v2.17.0@sha256:19f556d5852115c8ebbef271f6f7cf610d8803312a1fa63f29e1b342fe9d2939
    restart: unless-stopped
    env_file: etc/pocketid/.env
    environment:
      APP_URL: https://auth.fogtype.com
      TRUST_PROXY: 172.30.0.0/24,fded:a56c:7a13::/64
    volumes:
      - pocketid_data:/app/data
volumes:
  caddy_data:
  caddy_config:
  gotosocial_data:
  maddy_data:
  cocoon_data:
  headscale_data:
  pocketid_data:
networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
        - subnet: fded:a56c:7a13::/64
