name: fogtype
services:
  https:
    image: caddy:2.11.2-alpine@sha256:fce4f15aad23222c0ac78a1220adf63bae7b94355d5ea28eee53910624acedfa
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/udp"
      - "443:443/tcp"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./etc/caddy:/etc/caddy
      - ./srv:/srv
      - caddy_data:/data
      - caddy_config:/config
  gts:
    image: superseriousbusiness/gotosocial:0.21.1@sha256:4cc478b1305db641a44c863d7d43c44787db097432ac5473ccaddf7bf99c8178
    restart: unless-stopped
    environment:
      GTS_HOST: fogtype.com
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_TRUSTED_PROXIES: 172.30.0.0/24,fded:a56c:7a13::/64
    volumes:
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
      - ./etc/gotosocial:/etc/gotosocial
      - gotosocial_data:/gotosocial/storage
    command: "--config-path /etc/gotosocial/config.yaml"
  maddy:
    image: foxcpp/maddy:0.8.2@sha256:eeb5813fc4d101ec5d8f7b08b7255fd76ced2a06884ea94450c8a9a22fd6a08d
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    environment:
      MADDY_CONFIG: /etc/maddy/maddy.conf
      MADDY_HOSTNAME: fogtype.com
      MADDY_DOMAIN: fogtype.com
    volumes:
      - /etc/maddy:/etc/maddy
      - caddy_data:/var/lib/caddy/data:ro
      - maddy_data:/data
    entrypoint:
      - /bin/maddy
    command: run
  cocoon:
    image: ghcr.io/haileyok/cocoon:0.9.0@sha256:662a4186794c049a6a6ff8929185e45ab7ce2ce190876d39767c8d67f94a2808
    restart: unless-stopped
    env_file: etc/cocoon/.env
    volumes:
      - cocoon_data:/data
  headscale:
    image: headscale/headscale:v0.28.0@sha256:51b1b9182bb6219e97374fa89af6b9320d6f87ecc739e328d5357ea4fa7a5ce3
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "127.0.0.1:9200:9200"
    volumes:
      - ./etc/headscale:/etc/headscale
      - headscale_data:/var/lib/headscale
    command: serve
volumes:
  caddy_data:
  caddy_config:
  gotosocial_data:
  maddy_data:
  cocoon_data:
  headscale_data:
networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
        - subnet: fded:a56c:7a13::/64
