version: "3"
services:
  https:
    image: caddy:2.4.3-alpine@sha256:f00d2e7e82418a30135cbe5c1455df6c617ee651d6f430183a8e49e3b2608359
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/caddy:/etc/caddy
      - ./srv:/srv
      - caddy_data:/data
      - caddy_config:/config
      - minicharge_tmp:/tmp/minicharge
  minicharge:
    image: miniflux/miniflux:2.0.32@sha256:1da85593b4a68267d0e15009114351868f1cb749192c4689990855051c90a152
    restart: unless-stopped
    environment:
      LISTEN_ADDR: /tmp/miniflux.sock
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@/postgres?host=/tmp/postgresql
      RUN_MIGRATIONS: "1"
    volumes:
      - minicharge_tmp:/tmp
      - postgres_tmp:/tmp/postgresql
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.4-alpine@sha256:3d00e3d45ae9110319959507214e47decabb1189055ef39313642de0fdf98b28
    restart: unless-stopped
    healthcheck:
      test: pg_isready
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_tmp:/var/run/postgresql
      - postgres_data:/var/lib/postgresql/data
  dns.keiu.net:
    image: coredns/coredns:1.8.4@sha256:6e5a02c21641597998b4be7cb5eb1e7b02c0d8d23cce4dd09f4682d463798890
    restart: unless-stopped
    expose: ["443"]
    ports: ["853:853"]
    volumes:
      - ./etc/coredns:/etc/coredns
      - caddy_data:/var/lib/caddy/data
    command: "-conf /etc/coredns/Corefile"
volumes:
  caddy_data:
  caddy_config:
  minicharge_tmp:
  postgres_tmp:
  postgres_data:
