version: "3"
services:
  https:
    image: caddy:2.4.3-alpine@sha256:eb248d465d0eeb823c2e5d5576e67400f6b7c8562a9ab912fa5b7e0579f9501d
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/caddy:/etc/caddy
      - ./srv:/srv
      - caddy_data:/data
      - caddy_config:/config
      - minicharge_tmp:/tmp/minicharge
  minicharge:
    image: miniflux/miniflux:2.0.31@sha256:63dea50e3dbb472e60f6fff59726867f588f61b246a93141b050b5041eed422f
    restart: unless-stopped
    environment:
      LISTEN_ADDR: /tmp/miniflux.sock
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@/postgres?host=/tmp/postgresql
    volumes:
      - minicharge_tmp:/tmp
      - postgres_tmp:/tmp/postgresql
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.3-alpine@sha256:bcb6ecc4e7388db0fd91717468b8508bb5c6a1b37ab3eae8817af2c25d7fb7d8
    restart: unless-stopped
    healthcheck:
      test: pg_isready
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./etc/postgres/initdb.d:/docker-entrypoint-initdb.d
      - postgres_tmp:/var/run/postgresql
      - postgres_data:/var/lib/postgresql/data
volumes:
  caddy_data:
  caddy_config:
  minicharge_tmp:
  postgres_tmp:
  postgres_data:
