#!/bin/sh
set -eu

cd "$(dirname "$0")"

ENV_FILE=etc/pocketid/.env

if [ ! -f "$ENV_FILE" ]; then
	cp etc/pocketid/.env.example "$ENV_FILE"
	echo "ENCRYPTION_KEY=$(openssl rand -base64 32)" >>"$ENV_FILE"
	echo "Created $ENV_FILE"
fi
