server_url: https://net.fogtype.com
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9200
acl_policy_path: /etc/headscale/acls.json
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10
