server_url: https://net.fogtype.com
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9200
database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/db.sqlite
noise:
  private_key_path: /var/lib/headscale/noise_private.key
prefixes:
  v6: fd7a:115c:a1e0::/48
  v4: 100.64.0.0/10
  allocation: random
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  update_frequency: 24h
dns:
  magic_dns: false
  override_local_dns: false
